times = ('Palmeiras', 'Flamengo', 'Internacional', 'Grémio', 'São Paulo', 'Atlético MG', 'Atlético PR', 'Cruzeiro', 'Botafogo', 'Santos', 'Bahia', 'Fluminense', 'Corinthias', 'Chapecoense', 'Ceará', 'Vasco da Gama', 'Sport', 'América MG', 'Vitória', 'Paraná')
linha = ('-='*20)
print(linha)
print(f'Os 5 pimeiros colocados são: {times[:5]}')
print(linha)
print(f'Os 4 últimos colocados são: {times[-4:]}')
print(linha)
print(f'Times em ordem alfabética : {sorted(times)}')
print(linha)
print(f'O Chapecoense está na posição {times.index('Chapecoense') + 1}ª posição')
